# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/chris/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5457.51/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/chris/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5457.51/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chris/academics/PhD/codebase/phononSqueezing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chris/academics/PhD/codebase/phononSqueezing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/chris/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5457.51/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/chris/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5457.51/bin/cmake/linux/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/home/chris/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/212.5457.51/bin/cmake/linux/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chris/academics/PhD/codebase/phononSqueezing/CMakeFiles /home/chris/academics/PhD/codebase/phononSqueezing//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chris/academics/PhD/codebase/phononSqueezing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PhononSqueezing.out

# Build rule for target.
PhononSqueezing.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PhononSqueezing.out
.PHONY : PhononSqueezing.out

# fast build rule for target.
PhononSqueezing.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/build
.PHONY : PhononSqueezing.out/fast

src/calcGS.o: src/calcGS.cpp.o
.PHONY : src/calcGS.o

# target to build an object file
src/calcGS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/calcGS.cpp.o
.PHONY : src/calcGS.cpp.o

src/calcGS.i: src/calcGS.cpp.i
.PHONY : src/calcGS.i

# target to preprocess a source file
src/calcGS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/calcGS.cpp.i
.PHONY : src/calcGS.cpp.i

src/calcGS.s: src/calcGS.cpp.s
.PHONY : src/calcGS.s

# target to generate assembly for a file
src/calcGS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/calcGS.cpp.s
.PHONY : src/calcGS.cpp.s

src/checkSomeStuff.o: src/checkSomeStuff.cpp.o
.PHONY : src/checkSomeStuff.o

# target to build an object file
src/checkSomeStuff.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/checkSomeStuff.cpp.o
.PHONY : src/checkSomeStuff.cpp.o

src/checkSomeStuff.i: src/checkSomeStuff.cpp.i
.PHONY : src/checkSomeStuff.i

# target to preprocess a source file
src/checkSomeStuff.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/checkSomeStuff.cpp.i
.PHONY : src/checkSomeStuff.cpp.i

src/checkSomeStuff.s: src/checkSomeStuff.cpp.s
.PHONY : src/checkSomeStuff.s

# target to generate assembly for a file
src/checkSomeStuff.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/checkSomeStuff.cpp.s
.PHONY : src/checkSomeStuff.cpp.s

src/evalExpectation.o: src/evalExpectation.cpp.o
.PHONY : src/evalExpectation.o

# target to build an object file
src/evalExpectation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/evalExpectation.cpp.o
.PHONY : src/evalExpectation.cpp.o

src/evalExpectation.i: src/evalExpectation.cpp.i
.PHONY : src/evalExpectation.i

# target to preprocess a source file
src/evalExpectation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/evalExpectation.cpp.i
.PHONY : src/evalExpectation.cpp.i

src/evalExpectation.s: src/evalExpectation.cpp.s
.PHONY : src/evalExpectation.s

# target to generate assembly for a file
src/evalExpectation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/evalExpectation.cpp.s
.PHONY : src/evalExpectation.cpp.s

src/evalGSProps.o: src/evalGSProps.cpp.o
.PHONY : src/evalGSProps.o

# target to build an object file
src/evalGSProps.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/evalGSProps.cpp.o
.PHONY : src/evalGSProps.cpp.o

src/evalGSProps.i: src/evalGSProps.cpp.i
.PHONY : src/evalGSProps.i

# target to preprocess a source file
src/evalGSProps.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/evalGSProps.cpp.i
.PHONY : src/evalGSProps.cpp.i

src/evalGSProps.s: src/evalGSProps.cpp.s
.PHONY : src/evalGSProps.s

# target to generate assembly for a file
src/evalGSProps.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/evalGSProps.cpp.s
.PHONY : src/evalGSProps.cpp.s

src/mainSqueeze.o: src/mainSqueeze.cpp.o
.PHONY : src/mainSqueeze.o

# target to build an object file
src/mainSqueeze.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/mainSqueeze.cpp.o
.PHONY : src/mainSqueeze.cpp.o

src/mainSqueeze.i: src/mainSqueeze.cpp.i
.PHONY : src/mainSqueeze.i

# target to preprocess a source file
src/mainSqueeze.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/mainSqueeze.cpp.i
.PHONY : src/mainSqueeze.cpp.i

src/mainSqueeze.s: src/mainSqueeze.cpp.s
.PHONY : src/mainSqueeze.s

# target to generate assembly for a file
src/mainSqueeze.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/mainSqueeze.cpp.s
.PHONY : src/mainSqueeze.cpp.s

src/matrixOperations.o: src/matrixOperations.cpp.o
.PHONY : src/matrixOperations.o

# target to build an object file
src/matrixOperations.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/matrixOperations.cpp.o
.PHONY : src/matrixOperations.cpp.o

src/matrixOperations.i: src/matrixOperations.cpp.i
.PHONY : src/matrixOperations.i

# target to preprocess a source file
src/matrixOperations.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/matrixOperations.cpp.i
.PHONY : src/matrixOperations.cpp.i

src/matrixOperations.s: src/matrixOperations.cpp.s
.PHONY : src/matrixOperations.s

# target to generate assembly for a file
src/matrixOperations.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/matrixOperations.cpp.s
.PHONY : src/matrixOperations.cpp.s

src/onePhonon/evalDoccInGSOnePh.o: src/onePhonon/evalDoccInGSOnePh.cpp.o
.PHONY : src/onePhonon/evalDoccInGSOnePh.o

# target to build an object file
src/onePhonon/evalDoccInGSOnePh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/onePhonon/evalDoccInGSOnePh.cpp.o
.PHONY : src/onePhonon/evalDoccInGSOnePh.cpp.o

src/onePhonon/evalDoccInGSOnePh.i: src/onePhonon/evalDoccInGSOnePh.cpp.i
.PHONY : src/onePhonon/evalDoccInGSOnePh.i

# target to preprocess a source file
src/onePhonon/evalDoccInGSOnePh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/onePhonon/evalDoccInGSOnePh.cpp.i
.PHONY : src/onePhonon/evalDoccInGSOnePh.cpp.i

src/onePhonon/evalDoccInGSOnePh.s: src/onePhonon/evalDoccInGSOnePh.cpp.s
.PHONY : src/onePhonon/evalDoccInGSOnePh.s

# target to generate assembly for a file
src/onePhonon/evalDoccInGSOnePh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/onePhonon/evalDoccInGSOnePh.cpp.s
.PHONY : src/onePhonon/evalDoccInGSOnePh.cpp.s

src/onePhonon/setUpGlobalHamiltonianOnePh.o: src/onePhonon/setUpGlobalHamiltonianOnePh.cpp.o
.PHONY : src/onePhonon/setUpGlobalHamiltonianOnePh.o

# target to build an object file
src/onePhonon/setUpGlobalHamiltonianOnePh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/onePhonon/setUpGlobalHamiltonianOnePh.cpp.o
.PHONY : src/onePhonon/setUpGlobalHamiltonianOnePh.cpp.o

src/onePhonon/setUpGlobalHamiltonianOnePh.i: src/onePhonon/setUpGlobalHamiltonianOnePh.cpp.i
.PHONY : src/onePhonon/setUpGlobalHamiltonianOnePh.i

# target to preprocess a source file
src/onePhonon/setUpGlobalHamiltonianOnePh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/onePhonon/setUpGlobalHamiltonianOnePh.cpp.i
.PHONY : src/onePhonon/setUpGlobalHamiltonianOnePh.cpp.i

src/onePhonon/setUpGlobalHamiltonianOnePh.s: src/onePhonon/setUpGlobalHamiltonianOnePh.cpp.s
.PHONY : src/onePhonon/setUpGlobalHamiltonianOnePh.s

# target to generate assembly for a file
src/onePhonon/setUpGlobalHamiltonianOnePh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/onePhonon/setUpGlobalHamiltonianOnePh.cpp.s
.PHONY : src/onePhonon/setUpGlobalHamiltonianOnePh.cpp.s

src/onePhonon/setupBasicOpertorsOnePh.o: src/onePhonon/setupBasicOpertorsOnePh.cpp.o
.PHONY : src/onePhonon/setupBasicOpertorsOnePh.o

# target to build an object file
src/onePhonon/setupBasicOpertorsOnePh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/onePhonon/setupBasicOpertorsOnePh.cpp.o
.PHONY : src/onePhonon/setupBasicOpertorsOnePh.cpp.o

src/onePhonon/setupBasicOpertorsOnePh.i: src/onePhonon/setupBasicOpertorsOnePh.cpp.i
.PHONY : src/onePhonon/setupBasicOpertorsOnePh.i

# target to preprocess a source file
src/onePhonon/setupBasicOpertorsOnePh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/onePhonon/setupBasicOpertorsOnePh.cpp.i
.PHONY : src/onePhonon/setupBasicOpertorsOnePh.cpp.i

src/onePhonon/setupBasicOpertorsOnePh.s: src/onePhonon/setupBasicOpertorsOnePh.cpp.s
.PHONY : src/onePhonon/setupBasicOpertorsOnePh.s

# target to generate assembly for a file
src/onePhonon/setupBasicOpertorsOnePh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/onePhonon/setupBasicOpertorsOnePh.cpp.s
.PHONY : src/onePhonon/setupBasicOpertorsOnePh.cpp.s

src/setupElectronicOperatorsSmall.o: src/setupElectronicOperatorsSmall.cpp.o
.PHONY : src/setupElectronicOperatorsSmall.o

# target to build an object file
src/setupElectronicOperatorsSmall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/setupElectronicOperatorsSmall.cpp.o
.PHONY : src/setupElectronicOperatorsSmall.cpp.o

src/setupElectronicOperatorsSmall.i: src/setupElectronicOperatorsSmall.cpp.i
.PHONY : src/setupElectronicOperatorsSmall.i

# target to preprocess a source file
src/setupElectronicOperatorsSmall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/setupElectronicOperatorsSmall.cpp.i
.PHONY : src/setupElectronicOperatorsSmall.cpp.i

src/setupElectronicOperatorsSmall.s: src/setupElectronicOperatorsSmall.cpp.s
.PHONY : src/setupElectronicOperatorsSmall.s

# target to generate assembly for a file
src/setupElectronicOperatorsSmall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/setupElectronicOperatorsSmall.cpp.s
.PHONY : src/setupElectronicOperatorsSmall.cpp.s

src/timeEvolution.o: src/timeEvolution.cpp.o
.PHONY : src/timeEvolution.o

# target to build an object file
src/timeEvolution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/timeEvolution.cpp.o
.PHONY : src/timeEvolution.cpp.o

src/timeEvolution.i: src/timeEvolution.cpp.i
.PHONY : src/timeEvolution.i

# target to preprocess a source file
src/timeEvolution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/timeEvolution.cpp.i
.PHONY : src/timeEvolution.cpp.i

src/timeEvolution.s: src/timeEvolution.cpp.s
.PHONY : src/timeEvolution.s

# target to generate assembly for a file
src/timeEvolution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/timeEvolution.cpp.s
.PHONY : src/timeEvolution.cpp.s

src/timeStep.o: src/timeStep.cpp.o
.PHONY : src/timeStep.o

# target to build an object file
src/timeStep.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/timeStep.cpp.o
.PHONY : src/timeStep.cpp.o

src/timeStep.i: src/timeStep.cpp.i
.PHONY : src/timeStep.i

# target to preprocess a source file
src/timeStep.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/timeStep.cpp.i
.PHONY : src/timeStep.cpp.i

src/timeStep.s: src/timeStep.cpp.s
.PHONY : src/timeStep.s

# target to generate assembly for a file
src/timeStep.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/timeStep.cpp.s
.PHONY : src/timeStep.cpp.s

src/twoPhonons/evalDoccInGS.o: src/twoPhonons/evalDoccInGS.cpp.o
.PHONY : src/twoPhonons/evalDoccInGS.o

# target to build an object file
src/twoPhonons/evalDoccInGS.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/twoPhonons/evalDoccInGS.cpp.o
.PHONY : src/twoPhonons/evalDoccInGS.cpp.o

src/twoPhonons/evalDoccInGS.i: src/twoPhonons/evalDoccInGS.cpp.i
.PHONY : src/twoPhonons/evalDoccInGS.i

# target to preprocess a source file
src/twoPhonons/evalDoccInGS.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/twoPhonons/evalDoccInGS.cpp.i
.PHONY : src/twoPhonons/evalDoccInGS.cpp.i

src/twoPhonons/evalDoccInGS.s: src/twoPhonons/evalDoccInGS.cpp.s
.PHONY : src/twoPhonons/evalDoccInGS.s

# target to generate assembly for a file
src/twoPhonons/evalDoccInGS.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/twoPhonons/evalDoccInGS.cpp.s
.PHONY : src/twoPhonons/evalDoccInGS.cpp.s

src/twoPhonons/setUpGlobalHamiltonian.o: src/twoPhonons/setUpGlobalHamiltonian.cpp.o
.PHONY : src/twoPhonons/setUpGlobalHamiltonian.o

# target to build an object file
src/twoPhonons/setUpGlobalHamiltonian.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/twoPhonons/setUpGlobalHamiltonian.cpp.o
.PHONY : src/twoPhonons/setUpGlobalHamiltonian.cpp.o

src/twoPhonons/setUpGlobalHamiltonian.i: src/twoPhonons/setUpGlobalHamiltonian.cpp.i
.PHONY : src/twoPhonons/setUpGlobalHamiltonian.i

# target to preprocess a source file
src/twoPhonons/setUpGlobalHamiltonian.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/twoPhonons/setUpGlobalHamiltonian.cpp.i
.PHONY : src/twoPhonons/setUpGlobalHamiltonian.cpp.i

src/twoPhonons/setUpGlobalHamiltonian.s: src/twoPhonons/setUpGlobalHamiltonian.cpp.s
.PHONY : src/twoPhonons/setUpGlobalHamiltonian.s

# target to generate assembly for a file
src/twoPhonons/setUpGlobalHamiltonian.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/twoPhonons/setUpGlobalHamiltonian.cpp.s
.PHONY : src/twoPhonons/setUpGlobalHamiltonian.cpp.s

src/twoPhonons/setupBasicOpertors.o: src/twoPhonons/setupBasicOpertors.cpp.o
.PHONY : src/twoPhonons/setupBasicOpertors.o

# target to build an object file
src/twoPhonons/setupBasicOpertors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/twoPhonons/setupBasicOpertors.cpp.o
.PHONY : src/twoPhonons/setupBasicOpertors.cpp.o

src/twoPhonons/setupBasicOpertors.i: src/twoPhonons/setupBasicOpertors.cpp.i
.PHONY : src/twoPhonons/setupBasicOpertors.i

# target to preprocess a source file
src/twoPhonons/setupBasicOpertors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/twoPhonons/setupBasicOpertors.cpp.i
.PHONY : src/twoPhonons/setupBasicOpertors.cpp.i

src/twoPhonons/setupBasicOpertors.s: src/twoPhonons/setupBasicOpertors.cpp.s
.PHONY : src/twoPhonons/setupBasicOpertors.s

# target to generate assembly for a file
src/twoPhonons/setupBasicOpertors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/twoPhonons/setupBasicOpertors.cpp.s
.PHONY : src/twoPhonons/setupBasicOpertors.cpp.s

src/utils/setupOps.o: src/utils/setupOps.cpp.o
.PHONY : src/utils/setupOps.o

# target to build an object file
src/utils/setupOps.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/utils/setupOps.cpp.o
.PHONY : src/utils/setupOps.cpp.o

src/utils/setupOps.i: src/utils/setupOps.cpp.i
.PHONY : src/utils/setupOps.i

# target to preprocess a source file
src/utils/setupOps.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/utils/setupOps.cpp.i
.PHONY : src/utils/setupOps.cpp.i

src/utils/setupOps.s: src/utils/setupOps.cpp.s
.PHONY : src/utils/setupOps.s

# target to generate assembly for a file
src/utils/setupOps.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/utils/setupOps.cpp.s
.PHONY : src/utils/setupOps.cpp.s

src/utils/writeStuffToHdf5.o: src/utils/writeStuffToHdf5.cpp.o
.PHONY : src/utils/writeStuffToHdf5.o

# target to build an object file
src/utils/writeStuffToHdf5.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/utils/writeStuffToHdf5.cpp.o
.PHONY : src/utils/writeStuffToHdf5.cpp.o

src/utils/writeStuffToHdf5.i: src/utils/writeStuffToHdf5.cpp.i
.PHONY : src/utils/writeStuffToHdf5.i

# target to preprocess a source file
src/utils/writeStuffToHdf5.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/utils/writeStuffToHdf5.cpp.i
.PHONY : src/utils/writeStuffToHdf5.cpp.i

src/utils/writeStuffToHdf5.s: src/utils/writeStuffToHdf5.cpp.s
.PHONY : src/utils/writeStuffToHdf5.s

# target to generate assembly for a file
src/utils/writeStuffToHdf5.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PhononSqueezing.out.dir/build.make CMakeFiles/PhononSqueezing.out.dir/src/utils/writeStuffToHdf5.cpp.s
.PHONY : src/utils/writeStuffToHdf5.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... PhononSqueezing.out"
	@echo "... src/calcGS.o"
	@echo "... src/calcGS.i"
	@echo "... src/calcGS.s"
	@echo "... src/checkSomeStuff.o"
	@echo "... src/checkSomeStuff.i"
	@echo "... src/checkSomeStuff.s"
	@echo "... src/evalExpectation.o"
	@echo "... src/evalExpectation.i"
	@echo "... src/evalExpectation.s"
	@echo "... src/evalGSProps.o"
	@echo "... src/evalGSProps.i"
	@echo "... src/evalGSProps.s"
	@echo "... src/mainSqueeze.o"
	@echo "... src/mainSqueeze.i"
	@echo "... src/mainSqueeze.s"
	@echo "... src/matrixOperations.o"
	@echo "... src/matrixOperations.i"
	@echo "... src/matrixOperations.s"
	@echo "... src/onePhonon/evalDoccInGSOnePh.o"
	@echo "... src/onePhonon/evalDoccInGSOnePh.i"
	@echo "... src/onePhonon/evalDoccInGSOnePh.s"
	@echo "... src/onePhonon/setUpGlobalHamiltonianOnePh.o"
	@echo "... src/onePhonon/setUpGlobalHamiltonianOnePh.i"
	@echo "... src/onePhonon/setUpGlobalHamiltonianOnePh.s"
	@echo "... src/onePhonon/setupBasicOpertorsOnePh.o"
	@echo "... src/onePhonon/setupBasicOpertorsOnePh.i"
	@echo "... src/onePhonon/setupBasicOpertorsOnePh.s"
	@echo "... src/setupElectronicOperatorsSmall.o"
	@echo "... src/setupElectronicOperatorsSmall.i"
	@echo "... src/setupElectronicOperatorsSmall.s"
	@echo "... src/timeEvolution.o"
	@echo "... src/timeEvolution.i"
	@echo "... src/timeEvolution.s"
	@echo "... src/timeStep.o"
	@echo "... src/timeStep.i"
	@echo "... src/timeStep.s"
	@echo "... src/twoPhonons/evalDoccInGS.o"
	@echo "... src/twoPhonons/evalDoccInGS.i"
	@echo "... src/twoPhonons/evalDoccInGS.s"
	@echo "... src/twoPhonons/setUpGlobalHamiltonian.o"
	@echo "... src/twoPhonons/setUpGlobalHamiltonian.i"
	@echo "... src/twoPhonons/setUpGlobalHamiltonian.s"
	@echo "... src/twoPhonons/setupBasicOpertors.o"
	@echo "... src/twoPhonons/setupBasicOpertors.i"
	@echo "... src/twoPhonons/setupBasicOpertors.s"
	@echo "... src/utils/setupOps.o"
	@echo "... src/utils/setupOps.i"
	@echo "... src/utils/setupOps.s"
	@echo "... src/utils/writeStuffToHdf5.o"
	@echo "... src/utils/writeStuffToHdf5.i"
	@echo "... src/utils/writeStuffToHdf5.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

