#ifndef PHONONSQUEEZING_EVALGSPROPSONLYPHOT_H
#define PHONONSQUEEZING_EVALGSPROPS_H



void evalGSProps(const bool twoPhonons);

void evalGSPropsTemp();

#endif //PHONONSQUEEZING_EVALGSPROPSONLYPHOT_H
