#ifndef PHONONSQUEEZING_TIMEEVOLUTION2BANDS_H
#define PHONONSQUEEZING_TIMEEVOLUTION2BANDS_H

void calcTimeEvolution2Bands();

void calcTimeEvolutionAsOfWD();

#endif //PHONONSQUEEZING_TIMEEVOLUTION2BANDS_H
